name: Process Current Affairs

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  run-current-affairs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure to include your requirements.txt file in the repo

    - name: Set environment variables
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      run: echo "Environment variables set."

    - name: Run Current Affairs Script
      run: python script.py
