name: Process Current Affairs

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  run-current-affairs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug Environment Variables
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}"
        echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}"

    - name: Install Root Certificates
      # Fix SSL certificate issues by installing/updating certificates
      run: |
        sudo apt-get update
        sudo apt-get install --reinstall ca-certificates

    - name: Run Current Affairs Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      run: python main.py
