name: Process Current Affairs

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-current-affairs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up MongoDB
      run: |
        sudo apt-get update
        sudo apt-get install -y mongodb
        sudo service mongodb start

    - name: Set environment variables
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      run: echo "Environment variables set."

    - name: Run Current Affairs Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      run: python main.py
